#//=== just a basic to do list using input function , this is a very minimalistic and basic beginner version for conceptual understanding of topics===//

z =input("Enter your name :")
print("Welcome to the To do list" , z)
a = input("Enter the task you want to perform :").capitalize()
print("Task added successfully",a)
b = input("Enter the task you want to perform :").capitalize()
print("Task added successfully",b)
c = input("Enter the task you want to perform :").capitalize()
print("Task added successfully",c)
d = input("Enter the task you want to perform :").capitalize()
print("Task added successfully",d)
e = input("Enter the task you want to perform :").capitalize()
print("Task added successfully",e)
print("Your To do list is :")
print("1.",a)
print("2.",b)
print("3.",c)
print("4.",d)
print("5.",e)
x = input("Enter the tasks you have completed :" ).capitalize()
print("Congratulations on completing the task :",x)
y = input("Enter the task you have completed :").capitalize()
print("Congratulations on completing the task :",y)
z = input("Enter the task you have completed :").capitalize()
print("Congratulations on completing the task :",z)   

